### ISSUE TITLE
Cannot message inidividual friends/group chats that are not on a specific server

### ISSUE THREAD

**Issue by hamishmb** [MateriApps/OpenCord#16]
It seems I can't message individual friends or group chats when they aren't part of a server, but it might be me not knowing where to look.

Just a note, not a complaint because it's great to see something like this appear :)

**Comment by X1nto** [comment]
App is still in its very early states, so it's only natural some features are missing

**Comment by DiamondMiner88** [comment]
Tracked in status.md
