### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by jingoniii** [MateriApps/OpenCord#18]
I can't log in, idk why. What I know is I have a working internet connection. And to register button does not working, I think it just there as a display. Need to rework and stabilize the application. I love the concept and the lightness of it. I hope these matter will soon be fixed.

**Comment by X1nto** [comment]
Do you have 2FA?

**Comment by jingoniii** [comment]
> Do you have 2FA?

No I don't have. It doesn't seem like it actually function when after I filled in the necessary information and clicked log in. I clicked it multiple times but it doesn't load. I guess there is really a bug there even the register button does not function well.

**Comment by X1nto** [comment]
The register button isn't supposed to function, it's a placeholder until the feature is actually added. I assume you downloaded the 0.0.1 version? I might need some logs to see what's an issue

**Comment by DaniJohni** [comment]
Hey, I have the same problem, did you get the logs you need?

**Comment by jingoniii** [comment]
> Hey, I have the same problem, did you get the logs you need?

Sorry I don't have. Dunno how to get logs.

**Comment by DaniJohni** [comment]
Me neither. Hiw can we get the logs for you @X1nto?

**Comment by X1nto** [comment]
Instructions should be in #7

**Comment by DaniJohni** [comment]
Okay, I got the log file here:
[logcat.txt](https://github.com/MateriApps/OpenCord/files/8599130/logcat.txt)

**Comment by ps1-hagrid** [comment]
Also installed the latest debug APK and can't login. I guess a token login would help. I just see a captcha appear and disappear.

**Comment by X1nto** [comment]
> Okay, I got the log file here: [logcat.txt](https://github.com/MateriApps/OpenCord/files/8599130/logcat.txt)

Looks like it's a NPE inside an API to Domain mapper. Although I can't reproduce the issue. Will take a look.

**Comment by CorentinBrule** [comment]
maybe not a clue for this particular case but I had the same problem (nothing happens after pressing the login button, or after validating the Captcha that keeps blinking...) and after 5min of waiting (I had set up the logs recording) I was connected and everything works
