### ISSUE TITLE
General mod podge of potentional "bugs"

### ISSUE THREAD

**Issue by OoLunar** [MateriApps/OpenCord#34]
The app looks great! Loving the color palette and the login design. The whole reason why I checked out the app in the first place is that the official app has started to overheat my low-end phone, which causes my phone to restart. Here are a few bugs I've noticed in OpenCord:
- [ ] No friend DM's (unsure if they reach out to you)
- [ ] Logging in for the first time takes a bit for the guilds/channels to load
- [ ] Users don't have role colored names
- [ ] No "mark all as read" option on a server (which would be helpful to have since every channel is marked as "unread" when logging in)
- [ ] The app seems to freeze for 100ms or so when a new message is sent, giving off a single-threaded app vibe
- [ ] The swipe interaction is weird, working sometimes, ignoring your swipe other times
- [ ] Guilds aren't ordered as they are on mobile or desktop (I believe there's an undocumented endpoint for this)
- [ ] No obvious way to look at the channel topic
- [ ] Member list doesn't seem to function
- [ ] Mentions altogether don't seem to function correctly
- [ ] Codeblocks render inaccurately
- [ ] Buttons
- [ ] Stage channels render as normal channels
- [ ] Channels aren't appropriately hidden (say, when you don't have permission to view)
- [ ] Guilds without an icon do not produce the same icon that the official clients use
- [ ] Settings don't show anything
- [ ] Lack of message attachment support

OpenCore images:
https://cdn.discordapp.com/attachments/964960714047508494/974836234818039848/Screenshot_20220513-194915-915.png
https://cdn.discordapp.com/attachments/964960714047508494/974836235254243378/Screenshot_20220513-194931-376.png
https://cdn.discordapp.com/attachments/964960714047508494/974836235547865128/Screenshot_20220513-194941-104.png

Discord image (zoom):
https://cdn.discordapp.com/attachments/964960714047508494/974836637735460964/Screenshot_20220513-195235-485.png

Other than these things, the app is really good. The only things that are truly stopping me from using the app as a daily driver is the lack of DM support and the "mark channels as read" option. I understand well that the app is far from finished and I'm looking forward to the finished product. I would love to contribute however I'm more of a C# developer than someone who uses Java (additionally I've never even touched UI, so I could only help clean up logical/simple operations).

Keep up the great work! You're doing amazing. DN

**Comment by ItzOnlyAnimal** [comment]
Some of these are a work in progress, others like the app freezing are known but have yet to be acknowledged yet (to me it seems like the whole chat gets refreshed on message send)

**Comment by DiamondMiner88** [comment]
Opencord is still in early development and is obviously not meant to be used as a daily driver.
(as pointed out by the status list in the README)
All of these are planned features.

**Comment by X1nto** [comment]
Closing this issue as most of these stuff is pointed out in the readme (the app is nowhere near to being a daily driver) and it's hard to keep an issue with multiple bug reports at the same time.
