### ISSUE TITLE
Why does the Readme say OpenCord is against the Discord ToS?

### ISSUE THREAD

**Issue by 12932** [MateriApps/OpenCord#43]
https://github.com/MateriApps/OpenCord#is-this-against-discord-tos

I read the Discord ToS and it doesn't prohibit third-party clients anywhere, could you please point me to the Discord ToS clause that prohibits this?

Or does OpenCord violate Discord ToS for other reasons? If so which ones

**Comment by X1nto** [comment]
"create derivative works based upon", since OpenCord derives from stock Discord client in one way or another. I believe the decompilation part counts too.

**Comment by DiamondMiner88** [comment]
Either way Discord doesn't care if it doesn't make strange requests/abuse the api

**Comment by Jan200101** [comment]
What does OpenCord derive from the Discord App?
If it were to derive from it it could be licensed under the GPLv3.
