### ISSUE TITLE
Consider using the fosscord api & implementation

### ISSUE THREAD

**Issue by SpookySkeletons** [MateriApps/OpenCord#62]
Have you considered using the fosscord api and implementation as a git submodule to help save time and sanity?

Projects like webcord wire up to this already and appear to successfully support all daily usability features.

**Comment by MaddyUnderStars** [comment]
The goal of fosscord is to be entirely backwards compatible with all discord.com clients. Asking clients to add fosscord support goes against this. We also already have a PR in the works to get opencord and the discord.com client working properly.
