### ISSUE TITLE
Create Relases

### ISSUE THREAD

**Issue by Florian-Sabonchi** [MateriApps/OpenCord#63]
Plesse create relases to download diektly

**Comment by daBroma** [comment]
https://nightly.link/materiapps/opencord/workflows/android/master/discord.zip

**Comment by Florian-Sabonchi** [comment]
> https://nightly.link/materiapps/opencord/workflows/android/master/discord.zip

Hi, thats not a release 

https://www.toolsqa.com/git/github-releases/

**Comment by daBroma** [comment]
Well as the project is not stable OpenCord will not do releases. Only test builds via GitHub Actions. Download it there or wait till the project is stable for a stable release.

**Comment by DiamondMiner88** [comment]
Yeah and opencord is nowhere close to a release

**Comment by Florian-Sabonchi** [comment]
Okay, no Problem perhaps it woud be usefull to Mention

**Comment by daBroma** [comment]
I am sure that OpenCord developers know how to create releaaes. Thanks for your concern though.
