### ISSUE TITLE
How can I download the app?

### ISSUE THREAD

**Issue by Drangonfly30** [MateriApps/OpenCord#76]
I want to try this app but as the released version is outdated also not usable(I couldn't login) and I can't find anything in action tab. So, how can I downland this app?

**Comment by lexisother** [comment]
...it's right there?
![image](https://user-images.githubusercontent.com/54973868/190992757-c3e83be0-1ef2-4b57-91e0-b97e1a7fe914.png)

**Comment by X1nto** [comment]
> I want to try this app but as the released version is outdated also not usable(I couldn't login) and I can't find anything in action tab. So, how can I downland this app?

You need to be logged in to download the latest build, alternatively you can use https://nightly.link/materiapps/opencord/workflows/android/master/discord.zip

**Comment by Drangonfly30** [comment]
Sorry but where do I have to tap to download app?

**Comment by Drangonfly30** [comment]
I'm still not able to login tho

**Comment by X1nto** [comment]
use the link I provided above

**Comment by ItzOnlyAnimal** [comment]
guh do #52 when
